//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicine.Clinic.Client.Model.VisitService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VisitService.IVisitService")]
    public interface IVisitService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitService/SearchVisits", ReplyAction="http://tempuri.org/IVisitService/SearchVisitsResponse")]
        string SearchVisits(string searchMrn, string searchPatientFirstName, string searchBllingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitService/SearchVisits", ReplyAction="http://tempuri.org/IVisitService/SearchVisitsResponse")]
        System.Threading.Tasks.Task<string> SearchVisitsAsync(string searchMrn, string searchPatientFirstName, string searchBllingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitService/SearchNewVisitProperties", ReplyAction="http://tempuri.org/IVisitService/SearchNewVisitPropertiesResponse")]
        string SearchNewVisitProperties();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitService/SearchNewVisitProperties", ReplyAction="http://tempuri.org/IVisitService/SearchNewVisitPropertiesResponse")]
        System.Threading.Tasks.Task<string> SearchNewVisitPropertiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitService/GetBillingNumber", ReplyAction="http://tempuri.org/IVisitService/GetBillingNumberResponse")]
        string GetBillingNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitService/GetBillingNumber", ReplyAction="http://tempuri.org/IVisitService/GetBillingNumberResponse")]
        System.Threading.Tasks.Task<string> GetBillingNumberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitService/EditVisit", ReplyAction="http://tempuri.org/IVisitService/EditVisitResponse")]
        string EditVisit(string billingNumber, string mrn, string doctorCode, int apartmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitService/EditVisit", ReplyAction="http://tempuri.org/IVisitService/EditVisitResponse")]
        System.Threading.Tasks.Task<string> EditVisitAsync(string billingNumber, string mrn, string doctorCode, int apartmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitService/GetPatientMrn", ReplyAction="http://tempuri.org/IVisitService/GetPatientMrnResponse")]
        string GetPatientMrn(string billingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitService/GetPatientMrn", ReplyAction="http://tempuri.org/IVisitService/GetPatientMrnResponse")]
        System.Threading.Tasks.Task<string> GetPatientMrnAsync(string billingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitService/GetDoctorCode", ReplyAction="http://tempuri.org/IVisitService/GetDoctorCodeResponse")]
        string GetDoctorCode(string billingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitService/GetDoctorCode", ReplyAction="http://tempuri.org/IVisitService/GetDoctorCodeResponse")]
        System.Threading.Tasks.Task<string> GetDoctorCodeAsync(string billingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitService/GetApartmentId", ReplyAction="http://tempuri.org/IVisitService/GetApartmentIdResponse")]
        int GetApartmentId(string billingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitService/GetApartmentId", ReplyAction="http://tempuri.org/IVisitService/GetApartmentIdResponse")]
        System.Threading.Tasks.Task<int> GetApartmentIdAsync(string billingNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitService/GetDefaultDoctorCode", ReplyAction="http://tempuri.org/IVisitService/GetDefaultDoctorCodeResponse")]
        string GetDefaultDoctorCode(int apartmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisitService/GetDefaultDoctorCode", ReplyAction="http://tempuri.org/IVisitService/GetDefaultDoctorCodeResponse")]
        System.Threading.Tasks.Task<string> GetDefaultDoctorCodeAsync(int apartmentId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVisitServiceChannel : Medicine.Clinic.Client.Model.VisitService.IVisitService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VisitServiceClient : System.ServiceModel.ClientBase<Medicine.Clinic.Client.Model.VisitService.IVisitService>, Medicine.Clinic.Client.Model.VisitService.IVisitService {
        
        public VisitServiceClient() {
        }
        
        public VisitServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VisitServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisitServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisitServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SearchVisits(string searchMrn, string searchPatientFirstName, string searchBllingNumber) {
            return base.Channel.SearchVisits(searchMrn, searchPatientFirstName, searchBllingNumber);
        }
        
        public System.Threading.Tasks.Task<string> SearchVisitsAsync(string searchMrn, string searchPatientFirstName, string searchBllingNumber) {
            return base.Channel.SearchVisitsAsync(searchMrn, searchPatientFirstName, searchBllingNumber);
        }
        
        public string SearchNewVisitProperties() {
            return base.Channel.SearchNewVisitProperties();
        }
        
        public System.Threading.Tasks.Task<string> SearchNewVisitPropertiesAsync() {
            return base.Channel.SearchNewVisitPropertiesAsync();
        }
        
        public string GetBillingNumber() {
            return base.Channel.GetBillingNumber();
        }
        
        public System.Threading.Tasks.Task<string> GetBillingNumberAsync() {
            return base.Channel.GetBillingNumberAsync();
        }
        
        public string EditVisit(string billingNumber, string mrn, string doctorCode, int apartmentId) {
            return base.Channel.EditVisit(billingNumber, mrn, doctorCode, apartmentId);
        }
        
        public System.Threading.Tasks.Task<string> EditVisitAsync(string billingNumber, string mrn, string doctorCode, int apartmentId) {
            return base.Channel.EditVisitAsync(billingNumber, mrn, doctorCode, apartmentId);
        }
        
        public string GetPatientMrn(string billingNumber) {
            return base.Channel.GetPatientMrn(billingNumber);
        }
        
        public System.Threading.Tasks.Task<string> GetPatientMrnAsync(string billingNumber) {
            return base.Channel.GetPatientMrnAsync(billingNumber);
        }
        
        public string GetDoctorCode(string billingNumber) {
            return base.Channel.GetDoctorCode(billingNumber);
        }
        
        public System.Threading.Tasks.Task<string> GetDoctorCodeAsync(string billingNumber) {
            return base.Channel.GetDoctorCodeAsync(billingNumber);
        }
        
        public int GetApartmentId(string billingNumber) {
            return base.Channel.GetApartmentId(billingNumber);
        }
        
        public System.Threading.Tasks.Task<int> GetApartmentIdAsync(string billingNumber) {
            return base.Channel.GetApartmentIdAsync(billingNumber);
        }
        
        public string GetDefaultDoctorCode(int apartmentId) {
            return base.Channel.GetDefaultDoctorCode(apartmentId);
        }
        
        public System.Threading.Tasks.Task<string> GetDefaultDoctorCodeAsync(int apartmentId) {
            return base.Channel.GetDefaultDoctorCodeAsync(apartmentId);
        }
    }
}
