//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicine.Clinic.Client.Model.SexService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoEntity", Namespace="http://schemas.datacontract.org/2004/07/Medicine.Clinic.Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Medicine.Clinic.Client.Model.SexService.DtoSex))]
    public partial class DtoEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoSex", Namespace="http://schemas.datacontract.org/2004/07/Medicine.Clinic.Service")]
    [System.SerializableAttribute()]
    public partial class DtoSex : Medicine.Clinic.Client.Model.SexService.DtoEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEdit {
            get {
                return this.IsEditField;
            }
            set {
                if ((this.IsEditField.Equals(value) != true)) {
                    this.IsEditField = value;
                    this.RaisePropertyChanged("IsEdit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SexService.ISexService")]
    public interface ISexService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISexService/FindSexes", ReplyAction="http://tempuri.org/ISexService/FindSexesResponse")]
        Medicine.Clinic.Client.Model.SexService.DtoSex[] FindSexes(Medicine.Clinic.Client.Model.SexService.DtoSex dtoSex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISexService/FindSexes", ReplyAction="http://tempuri.org/ISexService/FindSexesResponse")]
        System.Threading.Tasks.Task<Medicine.Clinic.Client.Model.SexService.DtoSex[]> FindSexesAsync(Medicine.Clinic.Client.Model.SexService.DtoSex dtoSex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISexService/EditSex", ReplyAction="http://tempuri.org/ISexService/EditSexResponse")]
        string EditSex(Medicine.Clinic.Client.Model.SexService.DtoSex dtoSex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISexService/EditSex", ReplyAction="http://tempuri.org/ISexService/EditSexResponse")]
        System.Threading.Tasks.Task<string> EditSexAsync(Medicine.Clinic.Client.Model.SexService.DtoSex dtoSex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISexService/GetSexByCode", ReplyAction="http://tempuri.org/ISexService/GetSexByCodeResponse")]
        Medicine.Clinic.Client.Model.SexService.DtoSex GetSexByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISexService/GetSexByCode", ReplyAction="http://tempuri.org/ISexService/GetSexByCodeResponse")]
        System.Threading.Tasks.Task<Medicine.Clinic.Client.Model.SexService.DtoSex> GetSexByCodeAsync(string code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISexServiceChannel : Medicine.Clinic.Client.Model.SexService.ISexService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SexServiceClient : System.ServiceModel.ClientBase<Medicine.Clinic.Client.Model.SexService.ISexService>, Medicine.Clinic.Client.Model.SexService.ISexService {
        
        public SexServiceClient() {
        }
        
        public SexServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SexServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SexServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SexServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Medicine.Clinic.Client.Model.SexService.DtoSex[] FindSexes(Medicine.Clinic.Client.Model.SexService.DtoSex dtoSex) {
            return base.Channel.FindSexes(dtoSex);
        }
        
        public System.Threading.Tasks.Task<Medicine.Clinic.Client.Model.SexService.DtoSex[]> FindSexesAsync(Medicine.Clinic.Client.Model.SexService.DtoSex dtoSex) {
            return base.Channel.FindSexesAsync(dtoSex);
        }
        
        public string EditSex(Medicine.Clinic.Client.Model.SexService.DtoSex dtoSex) {
            return base.Channel.EditSex(dtoSex);
        }
        
        public System.Threading.Tasks.Task<string> EditSexAsync(Medicine.Clinic.Client.Model.SexService.DtoSex dtoSex) {
            return base.Channel.EditSexAsync(dtoSex);
        }
        
        public Medicine.Clinic.Client.Model.SexService.DtoSex GetSexByCode(string code) {
            return base.Channel.GetSexByCode(code);
        }
        
        public System.Threading.Tasks.Task<Medicine.Clinic.Client.Model.SexService.DtoSex> GetSexByCodeAsync(string code) {
            return base.Channel.GetSexByCodeAsync(code);
        }
    }
}
