//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicine.Clinic.Client.Model.TubeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoEntity", Namespace="http://schemas.datacontract.org/2004/07/Medicine.Clinic.Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Medicine.Clinic.Client.Model.TubeService.DtoTube))]
    public partial class DtoEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoTube", Namespace="http://schemas.datacontract.org/2004/07/Medicine.Clinic.Service")]
    [System.SerializableAttribute()]
    public partial class DtoTube : Medicine.Clinic.Client.Model.TubeService.DtoEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VolumeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEdit {
            get {
                return this.IsEditField;
            }
            set {
                if ((this.IsEditField.Equals(value) != true)) {
                    this.IsEditField = value;
                    this.RaisePropertyChanged("IsEdit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Volume {
            get {
                return this.VolumeField;
            }
            set {
                if ((this.VolumeField.Equals(value) != true)) {
                    this.VolumeField = value;
                    this.RaisePropertyChanged("Volume");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TubeService.ITubeService")]
    public interface ITubeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITubeService/EditTube", ReplyAction="http://tempuri.org/ITubeService/EditTubeResponse")]
        string EditTube(Medicine.Clinic.Client.Model.TubeService.DtoTube dtoTube);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITubeService/EditTube", ReplyAction="http://tempuri.org/ITubeService/EditTubeResponse")]
        System.Threading.Tasks.Task<string> EditTubeAsync(Medicine.Clinic.Client.Model.TubeService.DtoTube dtoTube);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITubeService/FindTubes", ReplyAction="http://tempuri.org/ITubeService/FindTubesResponse")]
        Medicine.Clinic.Client.Model.TubeService.DtoTube[] FindTubes(Medicine.Clinic.Client.Model.TubeService.DtoTube dtoTube);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITubeService/FindTubes", ReplyAction="http://tempuri.org/ITubeService/FindTubesResponse")]
        System.Threading.Tasks.Task<Medicine.Clinic.Client.Model.TubeService.DtoTube[]> FindTubesAsync(Medicine.Clinic.Client.Model.TubeService.DtoTube dtoTube);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITubeService/GetTubeByCode", ReplyAction="http://tempuri.org/ITubeService/GetTubeByCodeResponse")]
        Medicine.Clinic.Client.Model.TubeService.DtoTube GetTubeByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITubeService/GetTubeByCode", ReplyAction="http://tempuri.org/ITubeService/GetTubeByCodeResponse")]
        System.Threading.Tasks.Task<Medicine.Clinic.Client.Model.TubeService.DtoTube> GetTubeByCodeAsync(string code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITubeServiceChannel : Medicine.Clinic.Client.Model.TubeService.ITubeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TubeServiceClient : System.ServiceModel.ClientBase<Medicine.Clinic.Client.Model.TubeService.ITubeService>, Medicine.Clinic.Client.Model.TubeService.ITubeService {
        
        public TubeServiceClient() {
        }
        
        public TubeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TubeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TubeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TubeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string EditTube(Medicine.Clinic.Client.Model.TubeService.DtoTube dtoTube) {
            return base.Channel.EditTube(dtoTube);
        }
        
        public System.Threading.Tasks.Task<string> EditTubeAsync(Medicine.Clinic.Client.Model.TubeService.DtoTube dtoTube) {
            return base.Channel.EditTubeAsync(dtoTube);
        }
        
        public Medicine.Clinic.Client.Model.TubeService.DtoTube[] FindTubes(Medicine.Clinic.Client.Model.TubeService.DtoTube dtoTube) {
            return base.Channel.FindTubes(dtoTube);
        }
        
        public System.Threading.Tasks.Task<Medicine.Clinic.Client.Model.TubeService.DtoTube[]> FindTubesAsync(Medicine.Clinic.Client.Model.TubeService.DtoTube dtoTube) {
            return base.Channel.FindTubesAsync(dtoTube);
        }
        
        public Medicine.Clinic.Client.Model.TubeService.DtoTube GetTubeByCode(string code) {
            return base.Channel.GetTubeByCode(code);
        }
        
        public System.Threading.Tasks.Task<Medicine.Clinic.Client.Model.TubeService.DtoTube> GetTubeByCodeAsync(string code) {
            return base.Channel.GetTubeByCodeAsync(code);
        }
    }
}
