//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicine.Clinic.Client.Model.IndicationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoEntity", Namespace="http://schemas.datacontract.org/2004/07/Medicine.Clinic.Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Medicine.Clinic.Client.Model.IndicationService.DtoIndication))]
    public partial class DtoEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoIndication", Namespace="http://schemas.datacontract.org/2004/07/Medicine.Clinic.Service")]
    [System.SerializableAttribute()]
    public partial class DtoIndication : Medicine.Clinic.Client.Model.IndicationService.DtoEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEdit {
            get {
                return this.IsEditField;
            }
            set {
                if ((this.IsEditField.Equals(value) != true)) {
                    this.IsEditField = value;
                    this.RaisePropertyChanged("IsEdit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IndicationService.IIndicationService")]
    public interface IIndicationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIndicationService/FindIndications", ReplyAction="http://tempuri.org/IIndicationService/FindIndicationsResponse")]
        Medicine.Clinic.Client.Model.IndicationService.DtoIndication[] FindIndications(Medicine.Clinic.Client.Model.IndicationService.DtoIndication dtoIndication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIndicationService/FindIndications", ReplyAction="http://tempuri.org/IIndicationService/FindIndicationsResponse")]
        System.Threading.Tasks.Task<Medicine.Clinic.Client.Model.IndicationService.DtoIndication[]> FindIndicationsAsync(Medicine.Clinic.Client.Model.IndicationService.DtoIndication dtoIndication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIndicationService/EditIndication", ReplyAction="http://tempuri.org/IIndicationService/EditIndicationResponse")]
        string EditIndication(Medicine.Clinic.Client.Model.IndicationService.DtoIndication dtoIndication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIndicationService/EditIndication", ReplyAction="http://tempuri.org/IIndicationService/EditIndicationResponse")]
        System.Threading.Tasks.Task<string> EditIndicationAsync(Medicine.Clinic.Client.Model.IndicationService.DtoIndication dtoIndication);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIndicationServiceChannel : Medicine.Clinic.Client.Model.IndicationService.IIndicationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IndicationServiceClient : System.ServiceModel.ClientBase<Medicine.Clinic.Client.Model.IndicationService.IIndicationService>, Medicine.Clinic.Client.Model.IndicationService.IIndicationService {
        
        public IndicationServiceClient() {
        }
        
        public IndicationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IndicationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndicationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Medicine.Clinic.Client.Model.IndicationService.DtoIndication[] FindIndications(Medicine.Clinic.Client.Model.IndicationService.DtoIndication dtoIndication) {
            return base.Channel.FindIndications(dtoIndication);
        }
        
        public System.Threading.Tasks.Task<Medicine.Clinic.Client.Model.IndicationService.DtoIndication[]> FindIndicationsAsync(Medicine.Clinic.Client.Model.IndicationService.DtoIndication dtoIndication) {
            return base.Channel.FindIndicationsAsync(dtoIndication);
        }
        
        public string EditIndication(Medicine.Clinic.Client.Model.IndicationService.DtoIndication dtoIndication) {
            return base.Channel.EditIndication(dtoIndication);
        }
        
        public System.Threading.Tasks.Task<string> EditIndicationAsync(Medicine.Clinic.Client.Model.IndicationService.DtoIndication dtoIndication) {
            return base.Channel.EditIndicationAsync(dtoIndication);
        }
    }
}
